
#create_clock -name clk_in -period 2.500 -waveform {0.0 1.25} [get_ports clk_in]
#create_clock -name clk_in_b -period 2.500 -waveform {1.25 0.0} [get_ports clk_in_b]

#create_clock -name clk_in -period 4.000 -waveform {0.00 2.00} [get_ports clk_in]
#create_clock -name clk_in_b -period 4.000 -waveform {2.00 0.00} [get_ports clk_in_b]

## contraints file for XCKU040 12-Port Router @ 400MHz Implementation



set_property PACKAGE_PIN AB10 [get_ports {Din_p[1]}]
set_property PACKAGE_PIN AB11 [get_ports {Din_p[2]}]
set_property PACKAGE_PIN AB15 [get_ports {Din_p[3]}]
set_property PACKAGE_PIN AC9 [get_ports {Din_p[4]}]
set_property PACKAGE_PIN AC13 [get_ports {Din_p[5]}]
set_property PACKAGE_PIN AE13 [get_ports {Din_p[6]}]
set_property PACKAGE_PIN AF10 [get_ports {Din_p[7]}]
set_property PACKAGE_PIN AG10 [get_ports {Din_p[8]}]
set_property PACKAGE_PIN AG12 [get_ports {Din_p[9]}]
set_property PACKAGE_PIN AH9 [get_ports {Din_p[10]}]
set_property PACKAGE_PIN AH14 [get_ports {Din_p[11]}]
set_property PACKAGE_PIN AB19 [get_ports {Dout_p[1]}]
set_property PACKAGE_PIN AA17 [get_ports {Dout_p[2]}]
set_property PACKAGE_PIN AB16 [get_ports {Dout_p[3]}]
set_property PACKAGE_PIN Y19 [get_ports {Dout_p[4]}]
set_property PACKAGE_PIN Y16 [get_ports {Dout_p[5]}]
set_property PACKAGE_PIN AC18 [get_ports {Dout_p[6]}]
set_property PACKAGE_PIN AC21 [get_ports {Dout_p[7]}]
set_property PACKAGE_PIN AD20 [get_ports {Dout_p[8]}]
set_property PACKAGE_PIN AE17 [get_ports {Dout_p[9]}]
set_property PACKAGE_PIN AC19 [get_ports {Dout_p[10]}]
set_property PACKAGE_PIN AE21 [get_ports {Dout_p[11]}]
set_property PACKAGE_PIN AE11 [get_ports {Sin_p[11]}]
set_property PACKAGE_PIN AA12 [get_ports {Sin_p[10]}]
set_property PACKAGE_PIN AE8 [get_ports {Sin_p[9]}]
set_property PACKAGE_PIN AG11 [get_ports {Sin_p[8]}]
set_property PACKAGE_PIN AF14 [get_ports {Sin_p[7]}]
set_property PACKAGE_PIN AD14 [get_ports {Sin_p[6]}]
set_property PACKAGE_PIN AE15 [get_ports {Sin_p[5]}]
set_property PACKAGE_PIN Y12 [get_ports {Sin_p[4]}]
set_property PACKAGE_PIN Y10 [get_ports {Sin_p[3]}]
set_property PACKAGE_PIN Y13 [get_ports {Sin_p[2]}]
set_property PACKAGE_PIN AA14 [get_ports {Sin_p[1]}]
set_property PACKAGE_PIN AG16 [get_ports {Sout_p[11]}]
set_property PACKAGE_PIN AG17 [get_ports {Sout_p[10]}]
set_property PACKAGE_PIN AH18 [get_ports {Sout_p[9]}]
set_property PACKAGE_PIN AG19 [get_ports {Sout_p[8]}]
set_property PACKAGE_PIN AF17 [get_ports {Sout_p[7]}]
set_property PACKAGE_PIN AG21 [get_ports {Sout_p[6]}]
set_property PACKAGE_PIN AH23 [get_ports {Sout_p[5]}]
set_property PACKAGE_PIN AF24 [get_ports {Sout_p[4]}]
set_property PACKAGE_PIN AF22 [get_ports {Sout_p[3]}]
set_property PACKAGE_PIN AD23 [get_ports {Sout_p[2]}]
set_property PACKAGE_PIN Y18 [get_ports {Sout_p[1]}]


set_property PACKAGE_PIN R25 [get_ports CLOCK_p]
set_property PACKAGE_PIN R26 [get_ports CLOCK_n]
set_property IOSTANDARD HSLVDCI_15 [get_ports CLOCK_n]
set_property IOSTANDARD HSLVDCI_15 [get_ports CLOCK_p]
set_property IOSTANDARD HSLVDCI_15 [get_ports rst_in]
set_property PACKAGE_PIN R27 [get_ports rst_in]

set_property PACKAGE_PIN AF13 [get_ports {Din_p[12]}]
set_property PACKAGE_PIN AF19 [get_ports {Dout_p[12]}]
set_property PACKAGE_PIN AD11 [get_ports {Sin_p[12]}]
set_property PACKAGE_PIN AD16 [get_ports {Sout_p[12]}]

